# Research Assistant Configuration

# Data Sources Configuration
sources:
  openalex:
    enabled: true
    timeout: 40
    max_results_per_source: 10
    base_url: "https://api.openalex.org/works"
    
  orkg:
    enabled: true
    timeout: 60
    max_results_per_source: 10
    base_url: "https://api.ask.orkg.org/index/search"
    retry_attempts: 3
    retry_delay: 1
    
  core:
    enabled: true
    timeout: 15
    max_results_per_source: 10
    base_url: "https://api.core.ac.uk/v3/search/works"
    retry_attempts: 3
    retry_delay: 1

# Default Search Parameters
defaults:
  max_results: 10
  min_year: 2004
  publication_types:
    - "journal"
    - "conference"

# Tool Behavior
behavior:
  parallel_execution: true
  max_workers: 3
  filter_duplicates: true
  sort_by_citations: false